language: csharp
sudo: false
dist: trusty
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
language: csharp
mono: none
dotnet: 2.1.300
script:
 - cd src/HttpFileRefresh
 - dotnet restore
 - dotnet build
 
